<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
	<CodeSnippet Format="1.0.1">
		<Header>
			<Title>appOnStartUp</Title>
			<Shortcut>appOnStartUp</Shortcut>
			<Description>Override WPF App OnStartUp</Description>
			<Author>Howe</Author>
			<SnippetTypes>
				<SnippetType>Expansion</SnippetType>
				<SnippetType>SurroundsWith</SnippetType>
			</SnippetTypes>
		</Header>
		<Snippet>
			<Declarations>
				<Literal>
					<ID>expression</ID>
					<ToolTip>Debug Write Line</ToolTip>
					<Default>true</Default>
				</Literal>
				
				<Literal Editable="false">
				  <ID>Dolores</ID>
				  <Default>$</Default>
				</Literal>
			</Declarations>
			
			<Code Language="csharp"><![CDATA[protected override void OnStartup(StartupEventArgs e)
        {
            #region 注册事件 - 捕获未处理的异常

            // 主线程
            this.DispatcherUnhandledException += new System.Windows.Threading.DispatcherUnhandledExceptionEventHandler(App_DispatcherUnhandledException);

            // 非主线程
            System.AppDomain.CurrentDomain.UnhandledException += new System.UnhandledExceptionEventHandler(CurrentDomain_UnhandledException);

            #endregion

            base.OnStartup(e);
        }

        #region 捕获未处理的异常

        /// <summary>
        /// 主线程
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        void App_DispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
        {
            try
            {
                HandleException("DispatcherUnhandledException", e.Exception);
                e.Handled = true;
            }
            catch (Exception ex)
            {
#if DEUBG
                string msg = $Dolores$"HandleException 发生异常。{ex.Message}";
                System.Diagnostics.Debug.WriteLine(msg);
                System.Diagnostics.Debugger.Break();
#endif
                throw ex;
            }
        }

        /// <summary>
        /// 非主线程
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            try
            {
                if (e.ExceptionObject is System.Exception)
                {
                    HandleException("CurrentDomain.UnhandledException", e.ExceptionObject as System.Exception);
                }
            }
            catch (Exception ex)
            {
#if DEUBG
                string msg = $Dolores$"HandleException 发生异常。{ex.Message}";
                System.Diagnostics.Debug.WriteLine(msg);
                System.Diagnostics.Debugger.Break();
#endif
                throw ex;
            }
        }

        public static void HandleException(string from, Exception ex)
        {
            Util.LogUtils.LogAsync
            (
                content: ex.GetFullInfo(),
                baseDirectory: System.IO.Path.Combine(Environment.CurrentDirectory, "crash")
            );

            MessageBox.Show
            (
                caption: "捕获到以下错误，请与管理员联系以获取帮助。",
                messageBoxText: $Dolores$"在 {from} 捕获到以下错误\r\n{ex.GetFullInfo()}"
            );
        }

        #endregion]]>
			</Code>
		</Snippet>
	</CodeSnippet>
</CodeSnippets>
